// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: pyserver/pyserver.proto

package pyserver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Epoch  int32    `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Layers []*Layer `protobuf:"bytes,2,rep,name=layers,proto3" json:"layers,omitempty"`
}

func (x *PushRequest) Reset() {
	*x = PushRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pyserver_pyserver_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRequest) ProtoMessage() {}

func (x *PushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pyserver_pyserver_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRequest.ProtoReflect.Descriptor instead.
func (*PushRequest) Descriptor() ([]byte, []int) {
	return file_pyserver_pyserver_proto_rawDescGZIP(), []int{0}
}

func (x *PushRequest) GetEpoch() int32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *PushRequest) GetLayers() []*Layer {
	if x != nil {
		return x.Layers
	}
	return nil
}

type PushReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *PushReply) Reset() {
	*x = PushReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pyserver_pyserver_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushReply) ProtoMessage() {}

func (x *PushReply) ProtoReflect() protoreflect.Message {
	mi := &file_pyserver_pyserver_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushReply.ProtoReflect.Descriptor instead.
func (*PushReply) Descriptor() ([]byte, []int) {
	return file_pyserver_pyserver_proto_rawDescGZIP(), []int{1}
}

func (x *PushReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type PullRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Epoch int32 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
}

func (x *PullRequest) Reset() {
	*x = PullRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pyserver_pyserver_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullRequest) ProtoMessage() {}

func (x *PullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pyserver_pyserver_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullRequest.ProtoReflect.Descriptor instead.
func (*PullRequest) Descriptor() ([]byte, []int) {
	return file_pyserver_pyserver_proto_rawDescGZIP(), []int{2}
}

func (x *PullRequest) GetEpoch() int32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

type PullReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Layers []*Layer `protobuf:"bytes,1,rep,name=layers,proto3" json:"layers,omitempty"`
}

func (x *PullReply) Reset() {
	*x = PullReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pyserver_pyserver_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullReply) ProtoMessage() {}

func (x *PullReply) ProtoReflect() protoreflect.Message {
	mi := &file_pyserver_pyserver_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullReply.ProtoReflect.Descriptor instead.
func (*PullReply) Descriptor() ([]byte, []int) {
	return file_pyserver_pyserver_proto_rawDescGZIP(), []int{3}
}

func (x *PullReply) GetLayers() []*Layer {
	if x != nil {
		return x.Layers
	}
	return nil
}

type Layer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DimBias   []int32   `protobuf:"varint,2,rep,packed,name=dim_bias,json=dimBias,proto3" json:"dim_bias,omitempty"`
	Bias      []float32 `protobuf:"fixed32,3,rep,packed,name=bias,proto3" json:"bias,omitempty"`
	DimKernel []int32   `protobuf:"varint,4,rep,packed,name=dim_kernel,json=dimKernel,proto3" json:"dim_kernel,omitempty"`
	Kernel    []float32 `protobuf:"fixed32,5,rep,packed,name=kernel,proto3" json:"kernel,omitempty"`
}

func (x *Layer) Reset() {
	*x = Layer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pyserver_pyserver_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Layer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Layer) ProtoMessage() {}

func (x *Layer) ProtoReflect() protoreflect.Message {
	mi := &file_pyserver_pyserver_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Layer.ProtoReflect.Descriptor instead.
func (*Layer) Descriptor() ([]byte, []int) {
	return file_pyserver_pyserver_proto_rawDescGZIP(), []int{4}
}

func (x *Layer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Layer) GetDimBias() []int32 {
	if x != nil {
		return x.DimBias
	}
	return nil
}

func (x *Layer) GetBias() []float32 {
	if x != nil {
		return x.Bias
	}
	return nil
}

func (x *Layer) GetDimKernel() []int32 {
	if x != nil {
		return x.DimKernel
	}
	return nil
}

func (x *Layer) GetKernel() []float32 {
	if x != nil {
		return x.Kernel
	}
	return nil
}

var File_pyserver_pyserver_proto protoreflect.FileDescriptor

var file_pyserver_pyserver_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x79, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x79, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x79, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x22, 0x4c, 0x0a, 0x0b, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x12, 0x27, 0x0a, 0x06, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x79, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x06, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x73, 0x22, 0x25, 0x0a, 0x09, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x23, 0x0a, 0x0b, 0x50, 0x75, 0x6c, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x22, 0x34, 0x0a,
	0x09, 0x50, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x27, 0x0a, 0x06, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x79, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x06, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x73, 0x22, 0x81, 0x01, 0x0a, 0x05, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x19, 0x0a, 0x08, 0x64, 0x69, 0x6d, 0x5f, 0x62, 0x69, 0x61, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x05, 0x52, 0x07, 0x64, 0x69, 0x6d, 0x42, 0x69, 0x61, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x62, 0x69, 0x61, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x02, 0x52, 0x04, 0x62, 0x69, 0x61, 0x73,
	0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x69, 0x6d, 0x5f, 0x6b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x05, 0x52, 0x09, 0x64, 0x69, 0x6d, 0x4b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x12,
	0x16, 0x0a, 0x06, 0x6b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x18, 0x05, 0x20, 0x03, 0x28, 0x02, 0x52,
	0x06, 0x6b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x32, 0x74, 0x0a, 0x06, 0x57, 0x6f, 0x72, 0x6b, 0x65,
	0x72, 0x12, 0x34, 0x0a, 0x04, 0x50, 0x75, 0x73, 0x68, 0x12, 0x15, 0x2e, 0x70, 0x79, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x13, 0x2e, 0x70, 0x79, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x75, 0x73, 0x68,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x04, 0x50, 0x75, 0x6c, 0x6c, 0x12,
	0x15, 0x2e, 0x70, 0x79, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x75, 0x6c, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x70, 0x79, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x50, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x28, 0x5a,
	0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4a, 0x69, 0x6a, 0x69,
	0x61, 0x5a, 0x61, 0x6e, 0x2f, 0x67, 0x6f, 0x64, 0x6d, 0x6c, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x70,
	0x79, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pyserver_pyserver_proto_rawDescOnce sync.Once
	file_pyserver_pyserver_proto_rawDescData = file_pyserver_pyserver_proto_rawDesc
)

func file_pyserver_pyserver_proto_rawDescGZIP() []byte {
	file_pyserver_pyserver_proto_rawDescOnce.Do(func() {
		file_pyserver_pyserver_proto_rawDescData = protoimpl.X.CompressGZIP(file_pyserver_pyserver_proto_rawDescData)
	})
	return file_pyserver_pyserver_proto_rawDescData
}

var file_pyserver_pyserver_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pyserver_pyserver_proto_goTypes = []interface{}{
	(*PushRequest)(nil), // 0: pyserver.PushRequest
	(*PushReply)(nil),   // 1: pyserver.PushReply
	(*PullRequest)(nil), // 2: pyserver.PullRequest
	(*PullReply)(nil),   // 3: pyserver.PullReply
	(*Layer)(nil),       // 4: pyserver.layer
}
var file_pyserver_pyserver_proto_depIdxs = []int32{
	4, // 0: pyserver.PushRequest.layers:type_name -> pyserver.layer
	4, // 1: pyserver.PullReply.layers:type_name -> pyserver.layer
	0, // 2: pyserver.Worker.Push:input_type -> pyserver.PushRequest
	2, // 3: pyserver.Worker.Pull:input_type -> pyserver.PullRequest
	1, // 4: pyserver.Worker.Push:output_type -> pyserver.PushReply
	3, // 5: pyserver.Worker.Pull:output_type -> pyserver.PullReply
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pyserver_pyserver_proto_init() }
func file_pyserver_pyserver_proto_init() {
	if File_pyserver_pyserver_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pyserver_pyserver_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pyserver_pyserver_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pyserver_pyserver_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pyserver_pyserver_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pyserver_pyserver_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Layer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pyserver_pyserver_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pyserver_pyserver_proto_goTypes,
		DependencyIndexes: file_pyserver_pyserver_proto_depIdxs,
		MessageInfos:      file_pyserver_pyserver_proto_msgTypes,
	}.Build()
	File_pyserver_pyserver_proto = out.File
	file_pyserver_pyserver_proto_rawDesc = nil
	file_pyserver_pyserver_proto_goTypes = nil
	file_pyserver_pyserver_proto_depIdxs = nil
}
